<a href="https://colab.research.google.com/github/FakerDeng/PracticalAI/blob/master/DeepLearning/07_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

In this lesson we'll learn about PyTorch which is a machine learning library used to build dynamic neural networks. We'll learn about the basics, like creating and using Tensors, in this lesson but we'll be making models with it in the next lesson.

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/pytorch.png" width=300>

# Tensor basics

In [1]:
# Load PyTorch library
!pip3 install torch

    100% |████████████████████████████████| 591.8MB 27kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x61a3a000 @  0x7f7ee89332a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


In [0]:
import numpy as np
import torch

In [3]:
# Creating a zero tensor
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[1.9397e-36, 0.0000e+00, 2.8026e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 4.7429e+30],
        [1.9431e-19, 4.7429e+30, 5.0938e-14, 0.0000e+00]])


In [5]:
# Creating a random tensor
x = torch.randn(2, 3) # normal distribution (rand(2,3) -> uniform distribution)
print (x)

tensor([[ 0.3741,  0.4332, -1.0846],
        [ 1.7711,  2.2129,  1.1181]])


In [6]:
# Zero and Ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
# NumPy array → Tensor
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.5294, 0.8304, 0.7119],
        [0.1898, 0.1084, 0.9061]], dtype=torch.float64)


In [9]:
# Changing tensor type
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor operations

In [10]:
# Addition
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[-1.6354, -1.5054,  2.5493],
        [-3.3250,  0.8498, -0.4265]])


In [13]:
# Dot product
x = torch.randn(2, 3)
print(x)
y = torch.randn(3, 2)
print(y)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

tensor([[ 0.6383,  0.6900, -1.1916],
        [ 0.0688, -0.7628,  2.8811]])
tensor([[ 1.1545, -0.1932],
        [-0.6981,  0.2758],
        [ 1.5788,  0.8413]])
Size: torch.Size([2, 2])
Values: 
tensor([[-1.6261, -0.9356],
        [ 5.1606,  2.2003]])


In [15]:
# Transpose
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.7698, -0.4652,  0.3771],
        [ 0.4786,  0.5386, -1.1820]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.7698,  0.4786],
        [-0.4652,  0.5386],
        [ 0.3771, -1.1820]])


In [16]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.7698, -0.4652],
        [ 0.3771,  0.4786],
        [ 0.5386, -1.1820]])


In [18]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape)) 
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape)) 
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [19]:
# Dimensional operations
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # add each row's value for every column
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # add each columns's value for every row
print("Values: \n{}".format(z))

Values: 
tensor([[ 0.9046,  1.0883, -1.3939],
        [ 1.4415, -0.2773, -0.1358]])
Values: 
tensor([ 2.3461,  0.8110, -1.5297])
Values: 
tensor([0.5990, 1.0284])


# Indexing, Splicing and Joining

In [20]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[-0.2229,  0.5214, -0.3479, -1.2507],
        [-0.5586, -0.4577,  0.1960,  1.1972],
        [-1.0463, -0.2876,  0.6885, -0.5256]])
x[:1]: 
tensor([[-0.2229,  0.5214, -0.3479, -1.2507]])
x[:1, 1:3]: 
tensor([[ 0.5214, -0.3479]])


In [21]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # values from (0, 0) & (2, 1)
print("Values: \n{}".format(chosen)) 

Values: 
tensor([[ 0.2381,  0.6723, -0.7752],
        [ 0.1098,  0.6890,  0.0775]])
Values: 
tensor([[ 0.2381, -0.7752],
        [ 0.1098,  0.0775]])
Values: 
tensor([0.2381, 0.0775])


In [22]:
# Concatenation
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # stack by rows (dim=1 to stack by columns)
print("Values: \n{}".format(y))

Values: 
tensor([[-0.7505,  1.1271, -0.3255],
        [-0.9973,  1.2125,  0.1335]])
Values: 
tensor([[-0.7505,  1.1271, -0.3255],
        [-0.9973,  1.2125,  0.1335],
        [-0.7505,  1.1271, -0.3255],
        [-0.9973,  1.2125,  0.1335]])


# Gradients

In [23]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be scalar
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.6791, 0.2886, 0.0833, 0.0613],
        [0.2767, 0.6063, 0.7889, 0.3708],
        [0.6792, 0.0235, 0.8437, 0.1315]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ y = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(y)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA tensors

In [24]:
# Is CUDA available?
print (torch.cuda.is_available())

True


If the code above return False, then go to `Runtime` → `Change runtime type` and select `GPU` under `Hardware accelerator`. 

In [25]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [26]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
